### ISSUE TITLE
Fix the counter of # of drew points in the screen

### ISSUE THREAD

**Issue by adalbertogonzaga** [adalbertogonzaga/the_chaos_game#4]
the counter is buggy because I did not knew how to properly update it. 
so instead of updating, the system is adding it multiple times , trying to overwrite the previous one, but it is ugly and not cool.

please check it on below image...
<img width="536" alt="image" src="https://user-images.githubusercontent.com/7495944/224877510-1395bdbc-523c-49c4-81bd-1296b4f9eca8.png">

**Comment by adalbertogonzaga** [comment]
@brunodrugowick , please take a look here. **help wanted** 😆

**Comment by brunodrugowick** [comment]
![image](https://user-images.githubusercontent.com/7481200/224880995-31d5e0f8-68ff-4a8f-8a69-cd60261aab44.png)

**Comment by adalbertogonzaga** [comment]
> ![image](https://user-images.githubusercontent.com/7481200/224880995-31d5e0f8-68ff-4a8f-8a69-cd60261aab44.png)

it is about the issue I've commented with you. The counter of number of dots added to the screen/image is not working correctly. Take a look and you'll remember 😜

**Comment by brunodrugowick** [comment]
![image](https://user-images.githubusercontent.com/7481200/224886452-d71d4b0d-5cce-42a1-83e4-03dc16950461.png)
